/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hfoss_posit_NativeLib */

#ifndef _Included_org_hfoss_posit_NativeLib
#define _Included_org_hfoss_posit_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hfoss_posit_NativeLib
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_hfoss_posit_NativeLib_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     org_hfoss_posit_NativeLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_hfoss_posit_NativeLib_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_hfoss_posit_NativeLib
 * Method:    startRWG
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_hfoss_posit_NativeLib_startRWG
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
