/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.hfoss.posit;

public final class R {
    public static final class array {
        public static final int bird_types=0x7f040001;
        public static final int observation_types=0x7f040002;
        public static final int types=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f050004;
        public static final int header_bg=0x7f050000;
        public static final int header_text=0x7f050001;
        public static final int link_color=0x7f050006;
        public static final int solid_blue=0x7f050008;
        public static final int solid_green=0x7f050009;
        public static final int solid_red=0x7f050007;
        public static final int solid_yellow=0x7f05000a;
        public static final int tablehead_bg=0x7f050002;
        public static final int tablehead_text=0x7f050003;
        public static final int white=0x7f050005;
    }
    public static final class drawable {
        public static final int about=0x7f020000;
        public static final int add=0x7f020001;
        public static final int binocular=0x7f020002;
        public static final int blue=0x7f02001b;
        public static final int box=0x7f020003;
        public static final int bubble=0x7f020004;
        public static final int camera_icon_32x32=0x7f020005;
        public static final int close=0x7f020006;
        public static final int db_32x32=0x7f020007;
        public static final int direction=0x7f020008;
        public static final int flag=0x7f020009;
        public static final int gallery=0x7f02000a;
        public static final int green=0x7f02001c;
        public static final int icon=0x7f02000b;
        public static final int maps=0x7f02000c;
        public static final int new_entry=0x7f02000d;
        public static final int notebook_32x32=0x7f02000e;
        public static final int photo=0x7f02000f;
        public static final int posit=0x7f020010;
        public static final int record=0x7f020011;
        public static final int red=0x7f02001a;
        public static final int redbutton=0x7f020012;
        public static final int save=0x7f020013;
        public static final int screen_background_black=0x7f02001e;
        public static final int shadow=0x7f020014;
        public static final int shape_1=0x7f020015;
        public static final int stat_happy=0x7f020016;
        public static final int stat_sad=0x7f020017;
        public static final int streaming=0x7f020018;
        public static final int translucent_background=0x7f02001f;
        public static final int transparent_background=0x7f020020;
        public static final int update=0x7f020019;
        public static final int yellow=0x7f02001d;
    }
    public static final class id {
        public static final int DescriptionText=0x7f080029;
        public static final int Logo=0x7f080017;
        public static final int SaveButton=0x7f08002a;
        public static final int about=0x7f080000;
        public static final int addNameButton=0x7f080037;
        public static final int addNewNameDialogCancelButton=0x7f080003;
        public static final int addNewNameDialogOkButton=0x7f080002;
        public static final int addNewNameDialogText=0x7f080001;
        public static final int addSightingButton=0x7f080018;
        public static final int admin_layout=0x7f080062;
        public static final int ageText=0x7f08003b;
        public static final int camera=0x7f080012;
        public static final int cameraButton=0x7f080042;
        public static final int cameraSightingButton=0x7f080055;
        public static final int camera_preview=0x7f080009;
        public static final int confirm=0x7f080024;
        public static final int contents_new_find=0x7f08002e;
        public static final int contents_new_sighting=0x7f080048;
        public static final int dateLabel=0x7f080032;
        public static final int dateLabelSighting=0x7f08004d;
        public static final int dateText=0x7f080033;
        public static final int dateTextSighting=0x7f08004e;
        public static final int description=0x7f08001d;
        public static final int descriptionLabel=0x7f08003f;
        public static final int descriptionText=0x7f080040;
        public static final int description_id=0x7f08000e;
        public static final int dialog_close_cross=0x7f080016;
        public static final int femaleRadioButton=0x7f08003e;
        public static final int found_entries=0x7f08000c;
        public static final int gallery=0x7f08000a;
        public static final int identifierLabel=0x7f080038;
        public static final int identifierText=0x7f080039;
        public static final int label1=0x7f08002b;
        public static final int labelSpinner=0x7f08002c;
        public static final int latitude=0x7f08001f;
        public static final int latitudeLabel=0x7f080030;
        public static final int latitudeLabelSighting=0x7f080049;
        public static final int latitudeText=0x7f080027;
        public static final int latitudeTextSighting=0x7f08004a;
        public static final int latitude_text=0x7f08001e;
        public static final int linear_layout_1=0x7f08002f;
        public static final int longitude=0x7f080021;
        public static final int longitudeLabel=0x7f080031;
        public static final int longitudeLabelSighting=0x7f08004b;
        public static final int longitudeText=0x7f080028;
        public static final int longitudeTextSighting=0x7f08004c;
        public static final int longitude_text=0x7f080020;
        public static final int maleRadioButton=0x7f08003d;
        public static final int manage_add_hospital_button=0x7f080060;
        public static final int manage_add_mci_button=0x7f08005f;
        public static final int manage_header=0x7f08005d;
        public static final int manage_layout=0x7f08005c;
        public static final int manage_table=0x7f08005e;
        public static final int mapButton=0x7f080041;
        public static final int mapSightingButton=0x7f080054;
        public static final int mapit=0x7f080022;
        public static final int mapper=0x7f080058;
        public static final int mapview=0x7f08001a;
        public static final int menu_opts_tabhost=0x01010000;
        public static final int nameLabel=0x7f080036;
        public static final int nameSectionSighting=0x7f080045;
        public static final int nameSpinner=0x7f08000f;
        public static final int nameSpinnerSighting=0x7f080046;
        public static final int nameText=0x7f080025;
        public static final int new_entry=0x7f080014;
        public static final int numberLabel=0x7f080034;
        public static final int numberLabelSighting=0x7f08004f;
        public static final int numberText=0x7f080035;
        public static final int numberTextSighting=0x7f080050;
        public static final int observationTypeSpinner=0x7f080051;
        public static final int ok_btn=0x7f08001c;
        public static final int progress_button=0x7f080008;
        public static final int record=0x7f080015;
        public static final int refresh_btn=0x7f08001b;
        public static final int row_id=0x7f08000d;
        public static final int save=0x7f080013;
        public static final int saveButton=0x7f080043;
        public static final int saveSightingButton=0x7f080056;
        public static final int screen=0x7f080004;
        public static final int select_button=0x7f080007;
        public static final int sexRadioGroup=0x7f08003c;
        public static final int sightingsMapper=0x7f080010;
        public static final int spinner1=0x7f08002d;
        public static final int spinnerText=0x7f080063;
        public static final int switcher=0x7f08000b;
        public static final int syncFindsButton=0x7f080064;
        public static final int syncImagesButton=0x7f080065;
        public static final int synchronize_layout=0x7f080061;
        public static final int taggedCheckBox=0x7f08003a;
        public static final int takepic=0x7f080023;
        public static final int text1=0x7f080011;
        public static final int two_buttons=0x7f080005;
        public static final int two_buttons2=0x7f080006;
        public static final int viewGalleryButton=0x7f080044;
        public static final int viewGallerySightingButton=0x7f080057;
        public static final int viewRecordButtonSighting=0x7f080047;
        public static final int viewSightingsButton=0x7f080019;
        public static final int view_header=0x7f08005a;
        public static final int view_layout=0x7f080059;
        public static final int view_table=0x7f08005b;
        public static final int weatherImage=0x7f080052;
        public static final int weatherText=0x7f080053;
        public static final int widget33=0x7f080026;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int add_new_name=0x7f030001;
        public static final int alert_dialog=0x7f030002;
        public static final int finds_list=0x7f030003;
        public static final int gallery=0x7f030004;
        public static final int image_gallery=0x7f030005;
        public static final int list_row=0x7f030006;
        public static final int list_sightings=0x7f030007;
        public static final int listfind_list=0x7f030008;
        public static final int loading=0x7f030009;
        public static final int main=0x7f03000a;
        public static final int mapper2=0x7f03000b;
        public static final int new_find=0x7f03000c;
        public static final int new_find2=0x7f03000d;
        public static final int new_find_sci=0x7f03000e;
        public static final int new_find_sci_2=0x7f03000f;
        public static final int new_sighting=0x7f030010;
        public static final int newfindmap=0x7f030011;
        public static final int preferences=0x7f030012;
        public static final int spinner_1=0x7f030013;
        public static final int synchronize=0x7f030014;
        public static final int test=0x7f030015;
    }
    public static final class string {
        public static final int about=0x7f06002d;
        public static final int addLabel=0x7f06001f;
        public static final int addNewNameLabel=0x7f060025;
        public static final int addSightingLabel=0x7f060026;
        public static final int ageLabel=0x7f060023;
        public static final int app_name=0x7f060000;
        /**     Useful for hiding some things for a while   
         */
        public static final int blankLabel=0x7f06002b;
        public static final int button_map=0x7f060003;
        public static final int button_picture=0x7f060002;
        public static final int camera=0x7f060017;
        public static final int cancel=0x7f060010;
        public static final int cancelLabel=0x7f06002a;
        public static final int confirm=0x7f06000f;
        public static final int defaultInstanceLabel=0x7f060028;
        public static final int descriptionLabel=0x7f060014;
        public static final int idLabel=0x7f06001c;
        public static final int identifierLabel=0x7f06001e;
        public static final int label_victim=0x7f060011;
        public static final int latitude=0x7f06000d;
        public static final int longitude=0x7f06000e;
        public static final int map=0x7f060016;
        public static final int map_overlay_own_name=0x7f060008;
        public static final int menu_about=0x7f060001;
        public static final int menu_camera=0x7f060006;
        public static final int menu_delete=0x7f060007;
        public static final int menu_listfinds=0x7f060005;
        public static final int menu_mapfinds=0x7f060009;
        public static final int menu_newfind=0x7f060004;
        public static final int nameLabel=0x7f06001d;
        public static final int numberLabel=0x7f060012;
        public static final int observationTypeLabel=0x7f060022;
        public static final int okLabel=0x7f060029;
        public static final int preferences=0x7f06000a;
        public static final int save=0x7f060015;
        public static final int saving_to_disk=0x7f06000c;
        public static final int servers=0x7f060018;
        public static final int sexLabel=0x7f060024;
        public static final int sync=0x7f060019;
        public static final int syncFindText=0x7f06001a;
        public static final int syncImagesText=0x7f06001b;
        public static final int taggedLabel=0x7f060021;
        public static final int typeLabel=0x7f060013;
        public static final int untitled=0x7f06000b;
        public static final int viewLabel=0x7f060020;
        public static final int viewSightingsLabel=0x7f060027;
        public static final int weatherLabel=0x7f06002c;
    }
    public static final class style {
        public static final int Theme=0x7f070000;
        public static final int Theme_Transparent=0x7f070001;
    }
}
