<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseproject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('title', 'string', 128, array('type' => 'string', 'notnull' => true, 'length' => '128'));
        $this->hasColumn('description', 'object', null, array('type' => 'object'));
        $this->hasColumn('created_date', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
        $this->hasColumn('updated_date', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

}