<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basedevice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('device');
        $this->hasColumn('imei', 'string', 128, array('type' => 'string', 'notnull' => true, 'unique' => true, 'length' => '128'));
        $this->hasColumn('name', 'string', 128, array('type' => 'string', 'length' => '128'));
        $this->hasColumn('auth_key', 'string', 128, array('type' => 'string', 'notnull' => true, 'unique' => true, 'length' => '128'));
        $this->hasColumn('registered_date', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

}